apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sensu-backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sensu-backend
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sensu-backend
          image: gcr.io/engineering-182923/sensu-go
          command: ["/opt/sensu/bin/sensu-backend", "start"]
          ports:
            - protocol: TCP
              containerPort: 8080
            - protocol: TCP
              containerPort: 8081
            - protocol: TCP
              containerPort: 3000
