apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensu-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensu-agent
    spec:
      containers:
        - name: sensu-agent
          image: gcr.io/engineering-182923/sensu-go
          command: ["/opt/sensu/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: sensuapp
